### ISSUE TITLE
Page break dans les paragraphes

### ISSUE THREAD

**Issue by Karduin** [flotpython/tools#2]
@parmentelat 
En rajoutant ça dans le préambule, on évite de couper un paragraphe en bas de page. Bon c'est plus cosmétique qu'autre chose.

```
\widowpenalties 1 10000
\raggedbottom
```

**Comment by parmentelat** [comment]
il faudrait essayer pour être sûr bien entendu, mais comme le contenu est très morcelé j'imagine que ça ne provoquera pas de dégât particulier

avec de nouveau découpage en deux morceaux course / tools, j'ai pas mal nettoyé
mais je réalise que tu n'as pas forcément les moyens de tester tout ce fourbis, si ?

**Comment by Karduin** [comment]
J'ai testé sur l'ancienne version ça fonctionne. Je vais essayer ta procédure et XeLaTeX.
Je vais relire le how-to pour bien assimiler la démarche parce-que là j'ai juste survolé...

**Comment by parmentelat** [comment]
> On 8 Nov 2018, at 16:33, Karduin <notifications@github.com> wrote:
> 
> J'ai testé sur l'ancienne version ça fonctionne. Je vais essayer ta procédure et XeLaTeX.
> Je vais relire le how-to pour bien assimiler la démarche parce-que là j'ai juste survolé...


ok d’accord avec plaisir

j’espère que ce ne sera pas trop galère à faire marcher chez toi;
toute cette glue est un peu bricolée, sachant que dans un premier temps j’ai fait ça pour moi,

donc ce n’est pas forcément très robuste
le coaur de la logique est dans le fichier tools/bashrc-utils
il faut principalement que tu définissees les variables COURSEDIR et TOOLSDIR (ça peut être fait dans ton .bashrc)

[[digression: d’ailleurs je réalise en écrivant ça que ce serait très améliorable si j’avais d’abord calculé TOOLSDIR à partir de bashrc-utils, et donné un défaut pour COURSEDIR qui soit un frère de TOOLSDIR; mais bon..]]

en plus c’est essentiellement du bash là derrière, et si tu es sur windows ça ne va pas le faire du tout
il ne faut pas que tu perdes du temps avec ça si c’est trop lourd à mettre en place
dans ce cas je pourrai aussi tester tes suggestions moi-même

— Merci
